name: AuthService-CI

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2




      - name: Build
        run: |
          cd auth
          ./gradlew build -x test
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2




      - name: Test
        run: |
          cd auth
          ./gradlew test
  sonarQube:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2




      - name: SonarQube
        run: |
          cd auth
          ./gradlew sonarqube -D sonar.projectKey=AuthService -D sonar.host.url=http://localhost:9000 -D sonar.login=4847ab1941205386060f04b167b64764faef08a4
  

  docker:
    runs-on: self-hosted
    needs: sonarQube
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd auth
          docker build -t auth .
          docker run -d -p 8081:8081 --rm --name dockerprojectauth projectauth
  after_script:
    runs-on: self-hosted
    needs: [build, test, sonarQube, docker]
    steps:
      - name: End CI
        run: echo "End CI"

